# Generated by Django 5.1.3 on 2024-11-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notice.course'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(blank=True, choices=[('assignment', 'Assignment'), ('lab_report', 'Lab Report'), ('class_test', 'Class Test'), ('presentation', 'Presentation'), ('exam', 'Exam'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
