# Generated by Django 5.1.3 on 2024-11-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customtoken', to='student.student'),
        ),
    ]
